# Промисы: обработка ошибок

Если в цепочке промис завершается с ошибкой, то управление переходит в ближайший обработчик ошибок.

## Неявный try…catch

Вокруг функции промиса и обработчиков находится невидимый `try..catch`. Если происходит исключение, то оно перехватывается, и промис считается отклоненным с этой ошибкой.

Например, этот код:

```
new Promise((resolve, reject) => {
  throw new Error("Ошибка!");
}).catch(alert); // Error: Ошибка!
```

…Работает так же, как и этот:

```
new Promise((resolve, reject) => {
  reject(new Error("Ошибка!"));
}).catch(alert); // Error: Ошибка!
```

"Невидимый `try..catch`" вокруг промиса автоматически перехватывает ошибку и превращает ее в отклоненный промис.

Это работает и в обработчиках.

Это происходит для всех ошибок, не только для тех, которые вызваны оператором `throw`.

Финальный `.catch` перехватывает как промисы, в которых вызван `reject`, так и случайные ошибки в обработчиках.

## Пробрасывание ошибок

Если мы выбросим `throw` внутри `catch`, то управление перейдет к следующему ближайшему обработчику ошибок. А если мы обработаем ошибку и завершим работу обработчика нормально, то продолжит работу ближайший успешный обработчик.

## Необработанные ошибки

Если ошибка не обработана, то JavaScript в этом случае сгенерирует глобальную ошибку.

В браузере такую ошибку можно отловить используя событие `unhandledrejection`:

```
window.addEventListener('unhandledrejection', function(event) {
  // объект события имеет два специальных свойства:
  alert(event.promise); // [object Promise] - промис, который сгенерировал ошибку
  alert(event.reason); // Error: Ошибка! - объект ошибки, которая не была обработана
});

new Promise(function() {
  throw new Error("Ошибка!");
}); // нет обработчика ошибок
```