# Обработка ошибок, "try..catch"

## Синтаксис «try…catch»

Конструкция `try..catch` состоит из двух основных блоков: `try`, и затем `catch`.

Работает она так: 

1. Сначала выполняется код внутри блока `try {...}`.
2. Если в нём нет ошибок, то блок `catch(err)` игнорируется: выполнение доходит до конца `try` и потом далее, полностью пропуская `catch`.
3. Если же в нём возникает ошибка, то выполнение `try` прерывается, и поток управления переходит в начало `catch(err)`. Переменная `err` (можно использовать любое имя) содержит объект ошибки с подробной информацией о произошедшем.

Т.о., при ошибке в блоке `try` скрипт не падает, и нас есть возможность обработать ошибку внутри `catch`

### `try..catch` работает только для ошибок, возникающих во время выполнения кода

Чтобы `try..catch` работал, код должен быть выполнимым. Другими словами, это должен быть корректный JS-код. 

Он не сработает, если код синтаксически неверен. JS-движок сначала читает код, а затем исполняет его. Ошибки, которые возникают во время фазы чтения, называются ошибками парсинга.

### `try..catch` работает синхронно 

Исключение, которое произойдет в коде, запланнированном `на будущее`, например в `setTimeout`, `try..catch` не поймает